/aruco_detector_node:
  ros__parameters:
    camera_info_topic_name: "/right/camera/color/camera_info"
    image_topic_name: "/right/camera/color/image_raw"
    camera_frame: "right_camera_color_optical_frame"
    marker_size: 0.08
    visualize: true
