# arms moveit config
# add new arm config below xarm6_config
xarm6_config:
    group_name: xarm6
    base_link_name: link_base
    joint_names:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
        - joint6
    end_effector_name: link6
    planner_id: "RRTConnectkConfigDefault"
    max_velocity: 0.3
    max_acceleration: 0.3
    named_poses:
        reset_pose: [0,0,0,0,0,0]
        detect_pose: [0,-105,-15,0,33,0]
        place_pose: [0,-2,-43,0,45,0]

gen3_config:
    group_name: arm
    base_link_name: kortex_base_link
    joint_names:
        - kortex_joint_1
        - kortex_joint_2
        - kortex_joint_3
        - kortex_joint_4
        - kortex_joint_5
        - kortex_joint_6
        - kortex_joint_7
    end_effector_name: kortex_end_effector_link
    planner_id: "RRTConnectkConfigDefault"
    max_velocity: 0.3
    max_acceleration: 0.3
    named_poses:
        zero: [0,0,0,0,0,0,0]
        reset_pose: [0,-75,0,130,0,35,-90]
        detect_pose: [0,-75,0,130,0,35,-90]
        place_pose: [0,15,0,130,0,35,-90]

left_arm_config:
    group_name: left_arm
    base_link_name: base_link
    joint_names:
        - left_joint_1
        - left_joint_2
        - left_joint_3
        - left_joint_4
        - left_joint_5
        - left_joint_6
        - left_joint_7
    end_effector_name: left_end_effector_link
    planner_id: "RRTConnectkConfigDefault"
    max_velocity: 0.2
    max_acceleration: 0.2
    named_poses:
        zero: [0,0,0,0,0,0,0]
        reset_pose: [-60,-90,90,-120,0,-40,90]
        detect_pose: [-60,-90,90,-120,0,-40,90]
        place_pose: [-60,-90,90,-120,0,-40,90]

right_arm_config:
    group_name: right_arm
    base_link_name: base_link
    joint_names:
        - right_joint_1
        - right_joint_2
        - right_joint_3
        - right_joint_4
        - right_joint_5
        - right_joint_6
        - right_joint_7
    end_effector_name: right_end_effector_link
    planner_id: "RRTConnectkConfigDefault"
    max_velocity: 0.2
    max_acceleration: 0.2
    named_poses:
        zero: [0,0,0,0,0,0,0]
        reset_pose: [-120,90,-90,120,0,40,-90]
        detect_pose: [-120,90,-90,120,0,40,-90]
        place_pose: [-120,90,-90,120,0,40,-90]