---
1804_product:
  git_repos:
   driver: # 设备、传感器的ROS驱动
      realsense_ros:
        url: https://git.robotplusplus.com.cn/drivers/drivers-ros/realsense-ros.git
        user: $robuster_git_user
        tag: rppv3.0.0
        other_exec:
        apt_pkgs: 
        apt_ros_pkgs: 
        python2_pip_pkgs:
        python3_pip_pkgs:
        local_path: $local_drivers_repos
     