---
1804_product:
  git_repos:
   driver: # 设备、传感器的ROS驱动
      robotiq85:
        url: https://git.robotplusplus.com.cn/drivers/drivers-ros/robotiq.git
        user:  $robuster_git_user
        tag: 
        other_exec:
        apt_pkgs: 
        apt_ros_pkgs: soem
        python2_pip_pkgs: 
        python3_pip_pkgs: pyserial pymodbus arrow
        local_path: $local_drivers_repos
