---
1804_product:
  git_repos:
   driver: # 设备、传感器的ROS驱动
      rslidar_sdk:
        url: https://git.robotplusplus.com.cn/drivers/robosense-lidar/rslidar_sdk.git
        user:  $robuster_git_user
        tag: 
        other_exec:
        apt_pkgs:  libyaml-cpp-dev libpcap-dev
        apt_ros_pkgs: 
        python2_pip_pkgs:
        python3_pip_pkgs:
        local_path: $local_drivers_repos
      