/lidar_clipping:
  ros__parameters:
    point_cloud_topic: /livox/lidar
    filtered_point_cloud_topic: /livox/lidar_filtered 
    lidar_type: livox
    max_x: 0.5
    max_y: 0.3
    max_z: 0.5
    min_x: -0.65
    min_y: -0.3
    min_z: 0.0
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    use_sim_time: false
