---
2204_product:
  git_repos:
   slam: # 建图定位ROS包
     FASTLIO2_ROS2: #ros2
       url: https://git.robotplusplus.com.cn/slam/fast-lio-sam/liangheming/FASTLIO2_ROS2.git
       user: $robuster_git_user
       tag: rpp-humble-dev
       local_path: $local_slam_repos
       other_exec:
       apt_pkgs: #libceres-dev
       apt_ros_pkgs: #sparse-bundle-adjustment
       python2_pip_pkgs:
       python3_pip_pkgs:
   