---
2204_product:
  git_repos:
   slam: # 建图定位ROS包
     slam_toolbox: #ros2
       url: https://git.robotplusplus.com.cn/slam/stevemacenski/slam_toolbox.git
       user: $robuster_git_user
       tag: rpp-humble
       local_path: $local_slam_repos
       other_exec:
       apt_pkgs:  libsuitesparse-dev   libceres-dev
       apt_ros_pkgs: #sparse-bundle-adjustment
       python2_pip_pkgs:
       python3_pip_pkgs: