---
brav_7601_s00x_3060_2204_image:
  env_map:
    user_debug: false #true or false
    robuster_git_user: rpp:shihe321
    local_drivers_repos: $HOME/rpp_ws/src/drivers
    local_robot_repos: $HOME/rpp_ws/src/robot
    local_slam_repos: $HOME/rpp_ws/src/slam
    local_navigation_repos: $HOME/rpp_ws/src/navigation
    local_manipulator_repos: $HOME/rpp_ws/src/manipulator
    local_application_repos: $HOME/rpp_ws/src/application
    local_vision_repos: $HOME/rpp_ws/src/vision
    local_tools_repos: $HOME/rpp_ws/src/tools
    locla_3rdparty_repos: $HOME/3rdparty
    locla_rpp_data: $HOME/rpp_data
    locla_rpp_tools: $HOME/rpp_tools
    locla_rpp_docs: $HOME/rpp_docs
    locla_rpp_logs: $HOME/rpp_logs
    locla_rpp_background: 2024_12_30_ubuntu2204_ros2_rpp.jpg #or rpp.jpg
    nvidia_gpu_model: 
    car_mode: robot
    system_architecture: Linux_amd64 # or Linux_arm64
    PS1_STRING: \\[\033[1;32m\\]\u\\[\033[1;36m\\]<\\[\033[1;32m\\]$car_mode\\[\033[1;36m\\]>:\\[\033[1;34m\\]\w\\[\033[0m\\]\\$ '
    apt_source_url: https://mirrors.tuna.tsinghua.edu.cn
    pip_source_url: https://pypi.tuna.tsinghua.edu.cn/simple
    rpp_tools_link: http://file.robotplusplus.com.cn/common_tools/1.1.0
    rpp_data_link: http://file.robotplusplus.com.cn/rpp_data/1.0.0
    nvidia_toolkit_link: http://file.robotplusplus.com.cn/nvidia/ubuntu18.04-cuda-11.4.0-cudnn-8.4.1.50-tensorrt-8.4.1.5-amd64/
    git_3rdparty_link: https://git.robotplusplus.com.cn/third-party
    ros2_source_url: https://mirrors.tuna.tsinghua.edu.cn/ros2/ubuntu
    ros_distro_version: humble
  depends_map : 
    debian_pkgs: 
      -  code_*.deb
      - nomachine_*.deb
      - SunloginClient_*.deb

    python2_pip_pkgs: 
       -
    python3_pip_pkgs: 
      - numpy
    apt_pkgs: 
      - openssh-server 
      - python3  python3-pip
      - htop tree
      - curl wget wireshark proxychains4
      - gawk vim 
      - git
      - gimp kazam   pcl-tools
      - net-tools
      - bleachbit #硬盘清理工具
      - libeigen3-dev 
      - libmodbus-dev libserial-dev
      - libfuse2
      - g++ gcc cmake
      - libompl-dev
      - parallel #备份还原脚本需要
    apt_ros_pkgs:
      # - ros-control position-controllers  effort-controllers  velocity-controllers
      # - gazebo-ros gazebo-ros-control
      # - moveit moveit-servo combined-robot-hw trac-ik-kinematics-plugin  joint-trajectory-controller
      # -  joint-state-controller effort-controllers   ros-controllers  joint-state-publisher-gui
      # - joy teleop-twist-joy
      # - ddynamic-reconfigure 
      - rqt*
      - gazebo-ros2-control gazebo-ros-pkgs
      - ros-base  test-msgs plotjuggler-ros  xacro  #is ros2
      - joint-state-publisher

    rpp_docs:
      - http://file.robotplusplus.com.cn/equipment_information/industrial_computer/ZOTAC/brav-7601-S002_asm/
      #- http://file.robotplusplus.com.cn/equipment%20information/camera/intel/REALSENSE/


  git_repos:
   3rdparty: # 存放需要源码编译的第三方库，如GTSAM, OpenCV, ceres 等。也包含一些设备的驱动程序，如librealsense, livox-SDK等
     serial: 
        url: https://git.robotplusplus.com.cn/third-party/wjwwood/serial.git
        user: $robuster_git_user
        tag: rpp_humble_dev
        local_path: $locla_3rdparty_repos
        other_exec: simple_3rdparty.build
        apt_pkgs:
        apt_ros_pkgs:
        python2_pip_pkgs:
        python3_pip_pkgs: 

     CH341SER: 
        url: https://git.robotplusplus.com.cn/third-party/juliagoda/CH341SER.git
        user: $robuster_git_user
        tag: 
        local_path: $locla_3rdparty_repos
        other_exec: ch340.build
        apt_pkgs: gcc-12
        apt_ros_pkgs:
        python2_pip_pkgs:
        python3_pip_pkgs: 

     livox-sdk2: 
        url: https://git.robotplusplus.com.cn/drivers/livox-sdk/livox-sdk2.git
        user: $robuster_git_user
        tag: 
        local_path: $locla_3rdparty_repos
        other_exec: simple_3rdparty.build
        apt_pkgs: 
        apt_ros_pkgs:
        python2_pip_pkgs:
        python3_pip_pkgs: 

     rpp_fast_migrate_record:
        url: https://git.robotplusplus.com.cn/others/rpp_fast_migrate_record.git
        user: $robuster_git_user
        tag: 
        local_path: $locla_rpp_tools
        other_exec: rpp_fast_migrate_record.build
        apt_pkgs:
        apt_ros_pkgs:
        python2_pip_pkgs:
        python3_pip_pkgs:


     gtsam: 
        url: https://git.robotplusplus.com.cn/third-party/borglab/gtsam.git
        user: $robuster_git_user
        tag: 4.2a9
        local_path: $locla_3rdparty_repos
        other_exec: gtsam_22_04.build
        apt_pkgs:
        apt_ros_pkgs:
        python2_pip_pkgs:
        python3_pip_pkgs: 

     Sophus: 
        url: https://git.robotplusplus.com.cn/third-party/strasdat/Sophus.git
        user: $robuster_git_user
        tag: 1.22.10
        local_path: $locla_3rdparty_repos
        other_exec: sophus.build
        apt_pkgs:
        apt_ros_pkgs:
        python2_pip_pkgs:
        python3_pip_pkgs: 
        
     btrfs_progs: 
        url: https://git.robotplusplus.com.cn/third-party/kdave/btrfs-progs.git
        user: $robuster_git_user
        tag: v6.12
        local_path: $locla_3rdparty_repos
        other_exec: btrf_progs.build
        apt_pkgs: python3-sphinx python3-sphinx-rtd-theme libext2fs-dev liblzo2-dev
        apt_ros_pkgs:
        python2_pip_pkgs:
        python3_pip_pkgs: 
