---
1804_product:
  git_repos:
   vision: # 仿真相关功能包
      realsense_gazebo_plugin:
        url: https://git.robotplusplus.com.cn/third-party/pal-robotics/realsense_gazebo_plugin.git
        user: $robuster_git_user
        tag: rppv3.0.0
        local_path: $local_vision_repos
        other_exec:
        apt_pkgs:
        apt_ros_pkgs: 
        python2_pip_pkgs:
        python3_pip_pkgs:
   