---
1804_product:
  git_repos:
   application: # 机器人综合演示demo ROS包
      bt_task_manager:
          url: https://git.robotplusplus.com.cn/robot-application/bt_task_manager.git
          user: $robuster_git_user
          tag: mmx5-feat-v3.0.1
          other_exec:
          apt_pkgs:
          apt_ros_pkgs: py-trees* moveit-commander rqt-py-trees
          python2_pip_pkgs:
          python3_pip_pkgs:
          local_path: $local_application_repos
   