---
1804_product:
  git_repos:
   tools:
    Easy Handeye:
      url: https://git.robotplusplus.com.cn/third-party/ifl-camp/easy_handeye.git
      user: $robuster_git_user
      tag:  
      local_path: $local_tools_repos
      other_exec:
      apt_pkgs:
      apt_ros_pkgs: aruco-ros
      python2_pip_pkgs: transforms3d
      python3_pip_pkgs:
   