---
2204_image:
  git_repos:
   3rdparty: 
     CH341SER: 
        url: https://git.robotplusplus.com.cn/third-party/juliagoda/CH341SER.git
        user: $robuster_git_user
        tag: 
        local_path: $locla_3rdparty_repos
        other_exec: ch340.build
        apt_pkgs: gcc-12
        apt_ros_pkgs:
        python2_pip_pkgs:
        python3_pip_pkgs: 
