---
2204_image:
  git_repos:
   3rdparty: 
     serial: 
        url: https://git.robotplusplus.com.cn/third-party/wjwwood/serial.git
        user: $robuster_git_user
        tag: rpp_humble_dev
        local_path: $locla_3rdparty_repos
        other_exec: simple_3rdparty.build
        apt_pkgs:
        apt_ros_pkgs:
        python2_pip_pkgs:
        python3_pip_pkgs: 
