---
2204_image:
  git_repos:
   3rdparty: 
     Sophus: 
        url: https://git.robotplusplus.com.cn/third-party/strasdat/Sophus.git
        user: $robuster_git_user
        tag: 1.22.10
        local_path: $locla_3rdparty_repos
        other_exec: sophus.build
        apt_pkgs:
        apt_ros_pkgs:
        python2_pip_pkgs:
        python3_pip_pkgs: 
