---
1804_product:
  git_repos:
   product: # 具体产品对应的描述包，bringup包
    mmx5_description:
      url: https://git.robotplusplus.com.cn/robuster/description/mmx5_description.git
      user: $robuster_git_user
      tag: melodic-devel
      other_exec:
      apt_pkgs:
      apt_ros_pkgs: 
      python2_pip_pkgs:
      python3_pip_pkgs:
      local_path: $local_robot_repos
