---
1804_product:
  git_repos:
   navigation: # 导航ROS包
     navigation_msgs:
       url: https://git.robotplusplus.com.cn/navigation/ros-planning/navigation_msgs.git
       user: $robuster_git_user
       tag: rppv3.0.0
       local_path: $local_navigation_repos
       other_exec:
       apt_pkgs: 
       apt_ros_pkgs:
       python2_pip_pkgs:
       python3_pip_pkgs:
  