---
1804_product:
  git_repos:
   navigation: # 导航ROS包
     teb_local_planner:
       url: https://git.robotplusplus.com.cn/navigation/rst-tu-dortmund/teb_local_planner.git
       user: $robuster_git_user
       tag: rppv3.0.0
       local_path: $local_navigation_repos
       other_exec:
       apt_pkgs: libsuitesparse-dev
       apt_ros_pkgs: costmap-converter mbf-costmap-core mbf-msgs  libg2o
       python2_pip_pkgs:
       python3_pip_pkgs:
    