---
1804_image:
  git_repos:
   3rdparty: 
     rpp_fast_migrate_record:
        url: https://git.robotplusplus.com.cn/others/rpp_fast_migrate_record.git
        user: $robuster_git_user
        tag: 
        local_path: $locla_rpp_tools
        other_exec: rpp_fast_migrate_record.build
        apt_pkgs:
        apt_ros_pkgs:
        python2_pip_pkgs:
        python3_pip_pkgs:
