---
2204_product:
  git_repos:
   tools:
    ira_laser_tools: #ros2
      url: https://git.robotplusplus.com.cn/third-party/nakai-omer/ira_laser_tools.git
      user: $robuster_git_user
      tag:  humble
      local_path: $local_tools_repos
      other_exec:
      apt_pkgs:
      apt_ros_pkgs:
      python2_pip_pkgs:
      python3_pip_pkgs:
    