---
2204_product:
  git_repos:
   tools:
    lidar_clipping: #ros2
      url: https://git.robotplusplus.com.cn/others/lidar_clipping.git
      user: $robuster_git_user
      tag:  
      local_path: $local_tools_repos
      other_exec:
      apt_pkgs:
      apt_ros_pkgs:
      python2_pip_pkgs:
      python3_pip_pkgs:
    