# Default initial positions for ea200's ros2_control fake system

initial_positions:
  left_joint_1: 0
  left_joint_2: 0
  left_joint_3: 0
  left_joint_4: 0
  left_joint_5: 0
  left_joint_6: 0
  left_joint_7: 0
  right_joint_1: 0
  right_joint_2: 0
  right_joint_3: 0
  right_joint_4: 0
  right_joint_5: 0
  right_joint_6: 0
  right_joint_7: 0