cloud_topic: /fastlio2/body_cloud
odom_topic: /fastlio2/lio_odom
map_frame: map
local_frame: local

key_pose_delta_deg: 5
key_pose_delta_trans: 0.2
loop_search_radius: 5.0
loop_time_tresh: 60.0
loop_score_tresh: 0.15
loop_submap_half_range: 5
submap_resolution: 0.1
min_loop_detect_duration: 5.0